export const FETCH_STYLE_LIST_REQUEST = 'FETCH_STYLE_LIST_REQUEST';
export const FETCH_STYLE_LIST_SUCCESS = 'FETCH_STYLE_LIST_SUCCESS';
export const FETCH_STYLE_LIST_FAILURE = 'FETCH_STYLE_LIST_FAILURE';