export const FETCH_CURRENT_PRODUCT_REQUEST = 'FETCH_CURRENT_PRODUCT_REQUEST';
export const FETCH_CURRENT_PRODUCT_SUCCESS = 'FETCH_CURRENT_PRODUCT_SUCCESS';
export const FETCH_CURRENT_PRODUCT_FAILURE = 'FETCH_CURRENT_PRODUCT_FAILURE';